# This is the configuration file for Azure Pipelines, used to run tests on
# macOS. Documentation to help understand this setup:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
#
# In addition to this configuration file, the "Build pull requests from forks
# of this repository" setting must also be enabled in the Azure DevOps project:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github#validate-contributions-from-forks

trigger: none # disable builds for branches

jobs:
- job: decision
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false
  - script: |
      echo "Test jobs:"
      ./wpt test-jobs | while read job; do
        echo "$job"
        echo "##vso[task.setvariable variable=$job;isOutput=true]true";
      done
    name: jobs
    displayName: 'List test jobs'

- template: tools/ci/azure/wptrunner_infrastructure.yml
  parameters:
    os: macOS
    dependsOn: decision
    condition: dependencies.decision.outputs['jobs.tools_unittest']
