# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
    - master

jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - script: |
      ./wpt test-jobs | while read job; do echo "##vso[task.setvariable variable=run_$job]true"; done
    displayName: './wpt test-jobs'
    name: testjobs

  - script: |
      sw_vers
      echo $RUN_LINT
      ./tools/ci/install.sh
    displayName: 'Install Safari Technology Preview'

  - script: ./tools/ci/safaridriver_status.sh
    displayName: 'SafariDriver status'

  - script: |
      #no_proxy='*' ./wpt run --yes --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
      # fail if safaridriver was left running (killall fails if it's not running)
      #killall -0 safaridriver 2> /dev/null && echo "ERROR: safaridriver left running" && exit 1
    displayName: 'infrastructure/ tests'

  - script: |
      ls $(Build.ArtifactStagingDirectory)
      touch $(Build.ArtifactStagingDirectory)/foo
    displayName: 'artifacts tests'

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=vsts
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'things'
