# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
    - master

jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - script: |
      ./wpt test-jobs | while read job; do echo "##vso[task.setvariable variable=run_$job]true"; done
    displayName: 'Run ./wpt test-jobs'

  - script: |
      ./tools/ci/install.sh
    condition: eq(variables['Run.Manifest'], 'true')
    displayName: 'Install Safari Technology Preview'

  - script: |
      ./wpt manifest --manifest MANIFEST.json
      # publish the manifest as an artifact
      cp MANIFEST.json $(Build.ArtifactStagingDirectory)
    displayName: 'Update manifest'

  - script: |
      no_proxy='*' ./wpt run --yes --manifest MANIFEST.json --no-manifest-update --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
      # fail if safaridriver was left running (killall fails if it's not running)
      #killall -0 safaridriver 2> /dev/null && echo "ERROR: safaridriver left running" && exit 1
    displayName: 'Run infrastructure/ tests'

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'artifacts'
