# This is the configuration file for Azure Pipelines, used to run tests on
# macOS. Documentation to help understand this setup:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/multiple-phases
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/index
#
# In addition to this configuration file, the "Build pull requests from forks
# of this repository" setting must also be enabled in the Azure DevOps project:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github#validate-contributions-from-forks

trigger: none # disable builds for branches

jobs:
- job: root

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - template: tools/ci/azure/checkout.yml

  - script: |
      echo "Test jobs:"
      ./wpt test-jobs | while read job; do
        echo "$job"
        echo "##vso[task.setvariable variable=$job;isOutput=true]true";
      done
    name: test_jobs
    displayName: 'List test jobs'

- job: infrastructure_macOS
  displayName: 'infrastructure/ tests (macOS)'
  dependsOn: root
  condition: dependencies.root.outputs['test_jobs.wptrunner_infrastructure']

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: tools/ci/azure/checkout.yml
  - template: tools/ci/azure/pip_install.yml
  - template: tools/ci/azure/install_fonts.yml
  - template: tools/ci/azure/install_certs.yml
  - template: tools/ci/azure/install_chrome.yml
  - template: tools/ci/azure/install_firefox.yml
  - template: tools/ci/azure/install_safari.yml
  - template: tools/ci/azure/update_hosts.yml

  - script: ./wpt manifest
    displayName: 'Update manifest'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=dev chrome infrastructure/
    displayName: 'Run infrastructure/ tests (Chrome Dev)'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=nightly firefox infrastructure/
    displayName: 'Run infrastructure/ tests (Firefox Nightly)'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
    displayName: 'Run infrastructure/ tests (Safari Technology Preview)'

- job: tools_unittest_macOS
  displayName: 'tools/ unittests (macOS)'
  dependsOn: root
  condition: dependencies.root.outputs['test_jobs.tools_unittest']

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: tools/ci/azure/checkout.yml

  - template: tools/ci/azure/pip_install.yml
    parameters:
      packages: tox virtualenv

  - script: tox -c tools/ -e py27 -- --junitxml=results.xml
    displayName: 'Run tools/ unittests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/results.xml'
      testRunTitle: 'tools/ pytest'
    displayName: 'Publish tools/ unittests results'

- job: wptrunner_unittest_macOS
  displayName: 'tools/wptrunner/ unittests (macOS)'
  dependsOn: root
  condition: dependencies.root.outputs['test_jobs.wptrunner_unittest']

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: tools/ci/azure/checkout.yml

  - template: tools/ci/azure/pip_install.yml
    parameters:
      packages: tox virtualenv

  - script: tox -c tools/wptrunner/ -e py27-base,py27-safari -- --junitxml=results.xml
    displayName: 'Run tools/wptrunner/ unittests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/wptrunner/results.xml'
      testRunTitle: 'tools/wptrunner/ pytest'
    displayName: 'Publish tools/wptrunner/ unittests results'

- job: wpt_integration_macOS
  displayName: 'tools/wpt/ tests (macOS)'
  dependsOn: root
  condition: dependencies.root.outputs['test_jobs.wpt_integration']

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - template: tools/ci/azure/checkout.yml

  - template: tools/ci/azure/pip_install.yml
    parameters:
      packages: tox virtualenv

  - template: tools/ci/azure/install_chrome.yml
  - template: tools/ci/azure/install_firefox.yml
  - template: tools/ci/azure/update_hosts.yml

  - script: tox -c tools/wpt/ -e py27 -- --junitxml=results.xml
    displayName: 'Run tools/wpt/ tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'tools/wpt/results.xml'
      testRunTitle: 'tools/wpt/ pytest'
    displayName: 'Publish tools/wpt/ test results'
