# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

trigger:
  branches:
    include:
    - master

jobs:
- job: macOS

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - script: |
      echo "Test jobs:"
      ./wpt test-jobs | tee test-jobs.txt
      cat test-jobs.txt | while read job; do echo "##vso[task.setvariable variable=run_$job]true"; done
      rm test-jobs.txt
    displayName: 'List test jobs'

  - script: |
      ./wpt manifest
    displayName: 'Update manifest'
    # stability is used as a proxy for whether there may be affected tests
    condition: or(variables.run_wptrunner_infrastructure, variables.run_stability)

  - script: |
      echo "Affected tests:"
      # TODO: `./wpt tests-affected --no-manifest-update`
      ./wpt tests-affected | tee tests-affected.txt
      # avoid running some later steps if there are no affected tests.
      [ -s tests-affected.txt ] && echo "##vso[task.setvariable variable=run_affected_tests]true"
      mv tests-affected.txt ..
    displayName: 'List affected tests'
    condition: variables.run_stability

  - script: |
      ./tools/ci/install.sh
    displayName: 'Install Safari Technology Preview'
    condition: or(variables.run_wptrunner_infrastructure, variables.run_affected_tests)

  - script: |
      no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
    displayName: 'Run infrastructure/ tests'
    condition: variables.run_wptrunner_infrastructure

  - script: |
      # TODO: https://github.com/web-platform-tests/wpt/issues/13564 here and below
      no_proxy='*' ./wpt run --yes --no-manifest-update --no-pause --no-restart-on-unexpected --no-fail-on-unexpected --log-wptreport=$(Build.ArtifactStagingDirectory)/wpt_report.json --channel=preview safari_webdriver `cat ../tests-affected.txt`
    displayName: 'Run affected tests'
    condition: variables.run_affected_tests

  - script: |
      git checkout --force `./wpt branch-point`
      # No --no-manifest-update because it does have to be updated now.
      # TODO: map renamed files in tests-affected.txt, or run `./wpt tests-affected HEAD@{1}`
      no_proxy='*' ./wpt run --yes --no-pause --no-restart-on-unexpected --no-fail-on-unexpected --log-wptreport=$(Build.ArtifactStagingDirectory)/wpt_report_without_changes.json --channel=preview safari_webdriver `cat ../tests-affected.txt`
    displayName: 'Run affected tests (without changes)'
    condition: variables.run_affected_tests
    continueOnError: true

    # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    condition: succeededOrFailed()
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'artifacts'
