osx_instance:
  image: high-sierra-xcode-9.4.1

safari_task:
  install_script:
    - brew tap foolip/homebrew-cask-versions
    - brew cask install safari-technology-preview
    # https://github.com/web-platform-tests/wpt/blob/master/docs/_running-tests/safari.md
    - sudo "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --enable
    - defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
    #- security add-trusted-cert -k "$(security default-keychain | cut -d\" -f2)" tools/certs/cacert.pem
    - sudo easy_install pip
    - RUN_JOB=1 sudo ./tools/ci/install.sh
    - ./wpt make-hosts-file | sudo tee -a /etc/hosts
  script:
    - no_proxy='*' ./wpt run --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --install-fonts --no-fail-on-unexpected --log-wptreport=wpt_report.json safari infrastructure/
