osx_instance:
  image: high-sierra-xcode-9.4.1

task:
  matrix:
    - name: infrastructure/ tests (Safari Technology Preview)
  install_script:
    - sw_vers
    - ./tools/ci/install.sh
  script:
    - no_proxy='*' ./wpt run --yes --install-fonts --manifest MANIFEST.json --metadata infrastructure/metadata/ --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" safari_webdriver infrastructure/

task:
  matrix:
    - name: test results (Safari Technology Preview)
  install_script:
    - ./tools/ci/install.sh
  script:
    - no_proxy='*' ./wpt run --yes --install-fonts --no-restart-on-unexpected --no-fail-on-unexpected --log-wptreport=../wpt_report.json --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" safari_webdriver shadow-dom/
  report_script:
    - ./tools/ci/ci_report.sh ../wpt_report.json
