dist: trusty
sudo: required
language: python
branches:
  only:
    - master
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  # This needs be sourced as it sets various env vars
  - . ./tools/ci/before_install.sh
install:
  - ./tools/ci/install.sh
matrix:
  fast_finish: true
  include:
    - name: "infrastructure/ tests (Safari TP)"
      os: osx
      language: generic
      env: JOB=lint SCRIPT=tools/ci/ci_lint.sh
script:
  - brew tap foolip/homebrew-cask-versions > /dev/null
  - brew cask install safari-technology-preview
  #- sudo ./tools/ci/safari-enable-automation.sh
  - sudo "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --enable
  # https://github.com/web-platform-tests/wpt/blob/master/docs/_running-tests/safari.md
  - defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
  #- security add-trusted-cert -k "$(security default-keychain | cut -d\" -f2)" tools/certs/cacert.pem
  - ./wpt make-hosts-file | sudo tee -a /etc/hosts
  - git fetch --tags
  - ./wpt manifest-download
  - no_proxy='*' ./wpt run --yes --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --install-fonts --metadata infrastructure/metadata/ --no-fail-on-unexpected --log-wptreport=wpt_report.json safari infrastructure/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
