dist: trusty
sudo: required
language: python
branches:
  only:
    - master
addons:
  hosts:
    - web-platform.test
    - www.web-platform.test
    - www1.web-platform.test
    - www2.web-platform.test
    - xn--n8j6ds53lwwkrqhv28a.web-platform.test
    - xn--lve-6lad.web-platform.test
before_install:
  # This needs be sourced as it sets various env vars
  - . ./tools/ci/before_install.sh
install:
  - ./tools/ci/install.sh
matrix:
  fast_finish: true
  include:
    - name: "infrastructure/ tests (Safari TP)"
      os: osx
      language: generic
      env: JOB=lint SCRIPT=tools/ci/ci_lint.sh
script:
  # Use STP 65, as safaridriver is broken in 66
  - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install https://raw.githubusercontent.com/Homebrew/homebrew-cask-versions/e73cea88817b781d59beb25fb2640681a1ef4da8/Casks/safari-technology-preview.rb
  # https://web-platform-tests.org/running-tests/safari.html
  - sudo "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" --enable
  - defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically 1
  # https://github.com/web-platform-tests/results-collection/blob/master/src/scripts/trust-root-ca.sh
  - sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain tools/certs/cacert.pem
  - ./wpt make-hosts-file | sudo tee -a /etc/hosts
  - no_proxy='*' ./wpt run --yes --install-fonts --manifest MANIFEST.json --metadata infrastructure/metadata/ --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" safari infrastructure/

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
