dist: trusty
sudo: required
language: python
branches:
  only:
    - master
before_install:
  # This needs be sourced as it sets various env vars
  - . ./tools/ci/before_install.sh
install:
  - sw_vers
  - ./tools/ci/install.sh
matrix:
  # The use of `if` conditionals to exclude jobs from master should align with
  # jobs unconditionally listed by `./wpt test-jobs`, regardless of affected
  # paths. (The reverse is not true, as the manifest job could run on PRs too.)
  fast_finish: true
  include:
    - name: "infrastructure/ tests (Safari TP)"
      os: osx
      language: generic
      env: no_proxy="*"
      script:
        - ./wpt run --yes --install-fonts --manifest MANIFEST.json --metadata infrastructure/metadata/ --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" safari_webdriver infrastructure/
    - name: "test results (Safari TP)"
      os: osx
      language: generic
      env: no_proxy="*"
      script:
        - ./wpt run --yes --install-fonts --no-restart-on-unexpected --no-fail-on-unexpected --log-unittest - --log-wptreport=../wpt_report.json --webdriver-binary "/Applications/Safari Technology Preview.app/Contents/MacOS/safaridriver" safari_webdriver shadow-dom/
        - ./tools/ci/ci_report.sh ../wpt_report.json
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/meta
notifications:
  email:
    on_success: never
    on_failure: always
