parameters:
  name: ''
  vmImage: ''
  displayName: ''
  dependsOn: ''
  condition: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - script: |
      sudo easy_install pip
      pip install --user tox virtualenv
      echo "##vso[task.prependpath]$HOME/Library/Python/2.7/bin"
    displayName: 'Install Python packages'

  - template: install_browsers.yml
  - template: install_certs.yml
  - template: install_fonts.yml

  - script: ./wpt make-hosts-file | sudo tee -a /etc/hosts
    displayName: 'Update /etc/hosts'

  - script: ./wpt manifest
    displayName: 'Update manifest'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=dev chrome infrastructure/
    displayName: 'Run infrastructure/ tests (Chrome Dev)'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=nightly firefox infrastructure/
    displayName: 'Run infrastructure/ tests (Firefox Nightly)'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
    displayName: 'Run infrastructure/ tests (Safari Technology Preview)'
