parameters:
  os: ''
  dependsOn: ''
  condition: ''

jobs:
- job: 'infrastructure_${{ parameters.os }}'
  displayName: 'infrastructure/ (${{ parameters.os }})'
  dependsOn: decision
  condition: dependencies.decision.outputs['jobs.tools_unittest']
  pool:
    ${{ if eq(parameters.os, 'macOS') }}:
      vmImage: 'macOS-10.13'
    ${{ if eq(parameters.os, 'Linux') }}:
      vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - template: install_virtualenv.yml
    parameters:
      os: ${{ parameters.os }}

  - template: install_browsers.yml
    parameters:
      os: ${{ parameters.os }}

  - template: install_certs.yml
    parameters:
      os: ${{ parameters.os }}

  - template: install_fonts.yml
    parameters:
      os: ${{ parameters.os }}

  - template: update_hosts.yml
    parameters:
      os: ${{ parameters.os }}

  - script: ./wpt manifest
    displayName: 'Update manifest'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=dev chrome infrastructure/
    displayName: 'Run infrastructure/ tests (Chrome Dev)'

  - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=nightly firefox infrastructure/
    displayName: 'Run infrastructure/ tests (Firefox Nightly)'

  - {{ if eq(parameters.os, 'macOS') }}:
    - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
      displayName: 'Run infrastructure/ tests (Safari Technology Preview)'
