parameters:
  os: ''

jobs:
- job: 'infrastructure_${{ parameters.os }}'
  displayName: 'infrastructure/ (${{ parameters.os }})'
  dependsOn: decision
  condition: dependencies.decision.outputs['jobs.tools_unittest']
  pool:
    ${{ if eq(parameters.os, 'macOS') }}:
      vmImage: 'macOS-10.13'
    ${{ if eq(parameters.os, 'Linux') }}:
      vmImage: 'ubuntu-16.04'
  steps:
  - checkout: self
    fetchDepth: 50
    submodules: false

  - ${{ if eq(parameters.os, 'Linux') }}:
    - script: |
        sudo apt-get install xvfb
        dpkg -L xvfb
      displayName: 'Install Xvfb'

    - script: sh -e /etc/init.d/xvfb start 1>&2
      displayName: 'Start Xvfb'

  - template: install_virtualenv.yml
    parameters:
      os: ${{ parameters.os }}

  - template: install_certs.yml
    parameters:
      os: ${{ parameters.os }}

  - template: install_fonts.yml
    parameters:
      os: ${{ parameters.os }}

  - template: update_hosts.yml
    parameters:
      os: ${{ parameters.os }}

  - script: ./wpt manifest
    displayName: 'Update manifest'

  - template: install_browser.yml
    parameters:
      os: ${{ parameters.os }}
      browser: 'chrome'

  - script: DISPLAY=:99.0 no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=dev chrome infrastructure/
    displayName: 'Run infrastructure/ tests (Chrome Dev)'

  - template: install_browser.yml
    parameters:
      os: ${{ parameters.os }}
      browser: 'firefox'

  - script: DISPLAY=:99.0 no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=nightly firefox infrastructure/
    displayName: 'Run infrastructure/ tests (Firefox Nightly)'

  - ${{ if eq(parameters.os, 'macOS') }}:
    - template: install_browser.yml
      parameters:
        os: ${{ parameters.os }}
        browser: 'safari'

    - script: no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --channel=preview safari_webdriver infrastructure/
      displayName: 'Run infrastructure/ tests (Safari Technology Preview)'
